import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {spawn} from 'node:child_process';
import {openCloudStore,databaseOptions} from '../cloud-store.mjs';
import {postgresFixture,freePort} from './postgres-fixture.mjs';
const root=fileURLToPath(new URL('..',import.meta.url));
fs.mkdirSync(path.join(root,'test-results'),{recursive:true});
test('PostgreSQL cloud persistence and two-device HTTP workflow',async t=>{
  const pg=await postgresFixture();process.env.ALLOW_LOCAL_DATABASE='true';
  let a=await openCloudStore(pg.url),b=await openCloudStore(pg.url);t.after(async()=>{await a?.close();await b?.close();await pg.stop();});
  const alice=await a.register('alice','correct-horse-123','电脑'),bob=await a.register('bob','correct-horse-234','手机');const lid=alice.workspaces[0].id;
  const team=async(actor,lib,type,data={})=>a.teamAction(actor.key,lib,{type,...data,revision:(await a.me(actor.key)).revision});
  const action=async(actor,lib,type,data={})=>a.action(actor.key,lib,{type,...data,rev:(await a.state(actor.key,lib)).state.rev,requestId:randomUUID()});
  let state=(await a.state(alice.key,lid)).state;
  await t.test('accounts survive restart without any local SQLite copy',async()=>{await a.close();a=await openCloudStore(pg.url);assert.equal((await a.login('alice','correct-horse-123','新手机')).user.id,alice.user.id);assert.equal((await b.state(bob.key,bob.workspaces[0].id)).state.parts.length,0);await assert.rejects(b.state(bob.key,lid),/权限/);});
  await t.test('BOM inbound creates parts and outbound really decrements',async()=>{let r=await action(alice,lid,'bom.post',{kind:'入库',locationId:state.locations[0].id,boards:50,rows:[{autoPart:{sku:'R-10K',name:'10K电阻',category:'电阻',mount:'贴片',value:'10k',package:'0603'},perBoard:2},{excluded:true,perBoard:1,autoPart:{sku:'screw'}}]});assert.equal(r.state.parts.length,1);assert.equal(r.state.stocks[0].qty,100);r=await action(alice,lid,'bom.post',{kind:'出库',boards:5,rows:[{stockId:r.state.stocks[0].id,perBoard:2},{excluded:true,perBoard:1}]});assert.equal(r.state.stocks[0].qty,90);state=r.state;});
  const invite=await team(alice,lid,'invite.create',{role:'member',days:7});await team(bob,bob.workspaces[0].id,'invite.join',{code:invite.code});
  await t.test('concurrent services serialize conflicting issues and deduplicate retries',async()=>{const one={type:'stock.post',kind:'出库',stockId:state.stocks[0].id,qty:60,rev:state.rev,requestId:randomUUID()},two={...one,requestId:randomUUID()};const results=await Promise.allSettled([a.action(alice.key,lid,one),b.action(bob.key,lid,two)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.find(x=>x.status==='rejected').reason.status,409);const won=results[0].status==='fulfilled';const retry=await b.action(won?alice.key:bob.key,lid,won?one:two);assert.equal(retry.duplicate,true);assert.equal(retry.state.stocks[0].qty,30);state=retry.state;});
  await t.test('database failure rolls back both ledger and stock',async()=>{await a.pool.query("CREATE OR REPLACE FUNCTION hub_test_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected write failure'; END $$");await a.pool.query('CREATE TRIGGER hub_fail_write BEFORE UPDATE ON hub_metadata FOR EACH ROW EXECUTE FUNCTION hub_test_fail()');try{await assert.rejects(action(alice,lid,'stock.post',{kind:'出库',stockId:state.stocks[0].id,qty:1}),/injected/);}finally{await a.pool.query('DROP TRIGGER hub_fail_write ON hub_metadata');await a.pool.query('DROP FUNCTION hub_test_fail()');}const after=(await b.state(alice.key,lid)).state;assert.equal(after.stocks[0].qty,30);assert.equal(after.orders.length,state.orders.length);assert.equal(after.rev,state.rev);});
  await t.test('cross-library transfer commits both ends and rejects invalid destinations',async()=>{const target=(await team(alice,lid,'library.create',{name:'项目组'})).workspaceId;const to=(await a.state(alice.key,target)).state;const request={stockId:state.stocks[0].id,qty:4,rev:state.rev,toRev:to.rev,toLibraryId:target,locationId:to.locations[0].id,requestId:randomUUID()};await assert.rejects(a.transfer(alice.key,lid,{...request,locationId:'invalid'}));assert.equal((await b.state(alice.key,lid)).state.stocks[0].qty,30);await a.transfer(alice.key,lid,request);assert.equal((await b.state(alice.key,lid)).state.stocks[0].qty,26);assert.equal((await b.state(alice.key,target)).state.stocks[0].qty,4);assert.equal((await b.transfer(alice.key,lid,request)).duplicate,true);});
  await t.test('approval has no early deduction; readonly and device revocation persist',async()=>{await team(alice,lid,'member.save',{userId:bob.user.id,role:'admin',locations:null,projects:null});await team(alice,lid,'policy.save',{approvals:true});const pending=await action(alice,lid,'stock.post',{kind:'损耗',stockId:state.stocks[0].id,qty:1});assert.equal(pending.pending,true);assert.equal(pending.state.stocks[0].qty,26);await assert.rejects(a.approve(alice.key,lid,pending.approvalId,'approve'),/不能审批/);await b.approve(bob.key,lid,pending.approvalId,'approve');assert.equal((await a.state(alice.key,lid)).state.stocks[0].qty,25);await team(alice,lid,'policy.save',{approvals:false});await team(alice,lid,'member.save',{userId:bob.user.id,role:'readonly',locations:null,projects:null});await assert.rejects(action(bob,lid,'stock.post',{kind:'出库',stockId:state.stocks[0].id,qty:1}),/只读/);});
  await t.test('backup restore and bulk issue preserve final counts',async()=>{const backup=await a.backup(alice.key,lid);await action(alice,lid,'stock.bulkPost',{kind:'出库',rows:backup.stocks.map(x=>({stockId:x.id,qty:x.qty}))});assert.equal((await b.state(alice.key,lid)).state.stocks[0].qty,0);await action(alice,lid,'library.restore',{backup});assert.equal((await b.state(alice.key,lid)).state.stocks[0].qty,25);assert.equal((await b.team(alice.key,lid)).backups.at(-1).reason,'恢复前自动备份');});
  await t.test('HTTPS certificate validation cannot be disabled for remote databases',()=>{assert.equal(databaseOptions('postgresql://u:p@example.com/db?sslmode=disable',true).ssl.rejectUnauthorized,true);assert.equal(databaseOptions(pg.url,true).ssl,false);assert.throws(()=>databaseOptions(''),/DATABASE_URL/);});
  await t.test('HTTP login, events, writes, restart persistence and migration',async()=>{
    const port=await freePort(),base='http://127.0.0.1:'+port;let child;
    const start=async()=>{let logs='';child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,DATABASE_URL:pg.url,PORT:String(port),HOST:'127.0.0.1',ALLOW_LOCAL_DATABASE:'true',PUBLIC_URL:'',RENDER_EXTERNAL_URL:''},windowsHide:true,stdio:['ignore','pipe','pipe']});child.stdout.on('data',()=>{});child.stderr.on('data',x=>logs+=x);for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)return;}catch{}if(child.exitCode!==null)throw Error(logs);await new Promise(r=>setTimeout(r,50));}throw Error('startup timeout '+logs);};
    const stop=async()=>{const proc=child;child=null;if(proc&&proc.exitCode===null&&proc.signalCode===null)await new Promise(r=>{proc.once('exit',r);proc.kill();});};t.after(stop);await start();
    async function call(ep,method='GET',body,jar=''){const r=await fetch(base+'/api/'+ep,{method,headers:{'Content-Type':'application/json','X-Workspace':lid,Cookie:jar},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}
    assert.equal((await call('health')).data.storage,'postgresql');const login=await call('auth/login','POST',{username:'alice',password:'correct-horse-123'});assert.equal(login.status,200);const jar=login.cookie;let current=(await call('state','GET',undefined,jar)).data.state;
    const controller=new AbortController(),resp=await fetch(base+'/api/events?workspace='+lid,{headers:{Cookie:jar},signal:controller.signal}),reader=resp.body.getReader();let seen='';const dec=new TextDecoder();const until=async text=>{const timer=setTimeout(()=>controller.abort(),10000);try{while(!seen.includes(text)){const x=await reader.read();if(x.done)throw Error('SSE ended');seen+=dec.decode(x.value);}}finally{clearTimeout(timer);}};
    try{await until('data: ');seen='';const r=await call('action','POST',{type:'stock.post',kind:'出库',stockId:current.stocks[0].id,qty:1,rev:current.rev,requestId:randomUUID()},jar);assert.equal(r.status,200);assert.equal(r.data.state.stocks[0].qty,24);await until('"rev":'+r.data.state.rev);}finally{controller.abort();await reader.cancel().catch(()=>{});}
    await stop();await start();assert.equal((await call('state','GET',undefined,jar)).data.state.stocks[0].qty,24);
    assert.equal((await call('auth/logout','POST',{},jar)).status,200);await stop();await start();assert.equal((await call('state','GET',undefined,jar)).status,401);
    const newAccount=await call('auth/register','POST',{username:'newcloud','password':'cloud-password-12'});assert.equal(newAccount.status,200);await stop();await start();assert.equal((await call('auth/login','POST',{username:'newcloud','password':'cloud-password-12'})).status,200);await stop();
  });
});
